part of 'widgets.dart';

/// Provides the functionality for handling events generated by Material buttons.
mixin _MaterialButtonMixin on _WrapperInterface {
  /// Meta cell for on pressed action cell
  MetaCell<void>? get press;

  /// Meta cell for on long press action cell
  MetaCell<void>? get longPress;

  /// Meta cell for on hover event
  MetaCell<bool>? get onHover;

  /// Meta cell for on focus change event
  MetaCell<bool>? get onFocusChange;

  /// Get the action cell representing the onPressed event
  ActionCell _pressActionCell(BuildContext context) => ActionCell(
    key: _ElevatedButtonCellKey(context, #press)
  );

  /// Get the action cell representing the onLongPress event
  ActionCell _longPressActionCell(BuildContext context) => ActionCell(
      key: _ElevatedButtonCellKey(context, #longPress)
  );

  /// Get the action cell representing the onHover event
  MutableCell<bool> _onHoverCell(BuildContext context) => MutableCell(false,
    key: _ElevatedButtonCellKey(context, #onHover)
  );

  /// Get the action cell representing the onFocusChange event
  MutableCell<bool> _onFocusChangeCell(BuildContext context) => MutableCell(false,
      key: _ElevatedButtonCellKey(context, #onFocusChange)
  );

  @override
  Widget build(BuildContext context) {
    if (press != null) {
      press!.inject(_pressActionCell(context));
    }

    if (longPress != null) {
      longPress!.inject(_longPressActionCell(context));
    }

    if (onHover != null) {
      onHover!.setCell(_onHoverCell(context));
    }

    if (onFocusChange != null) {
      onFocusChange!.setCell(_onFocusChangeCell(context));
    }

    return _buildWrappedWidget(context);
  }
}

/// Key identifying a cell which represents a button event.
class _ElevatedButtonCellKey extends CellKey2<BuildContext, Symbol> {
  _ElevatedButtonCellKey(super.value1, super.value2);
}